Repository Goorm-OGJG/Web-IDE, pull requests merged in 2023-09, with the labels that each got.

#5 Feat : OW-18 User, RefreshToken domain 생성
  back/src/main/java/com/ogjg/back/user/domain/RefreshToken.java
  back/src/main/java/com/ogjg/back/user/domain/User.java
Labels: enhancement

#6 Rename : application 확장자 변경
  back/src/main/resources/application.yml
Labels: enhancement

#7 Feat : OW-20 라우팅 파일 만들기
  front/src/App.tsx
  front/src/components/CountRef/CountRef.tsx
  front/src/components/Footer/Footer.style.tsx
  front/src/components/Footer/Footer.tsx
  front/src/components/Header/Header.tsx
  front/src/components/Input.tsx
  front/src/components/Section/Section.style.tsx
  front/src/components/Section/Section.tsx
  front/src/components/Timer/Timer.tsx
  front/src/components/TimerState/TimerState.tsx
  front/src/pages/CreateContainer/CreateContainer.tsx
  front/src/pages/EditContainer/EditContainer.tsx
  front/src/pages/FindPassword/FindPassword.tsx
  front/src/pages/Login/Login.tsx
  front/src/pages/Main/Main.tsx
  front/src/pages/MyPage/MyPage.tsx
  front/src/pages/New/New.style.tsx
  front/src/pages/New/New.tsx
  front/src/pages/New/components/Logo/Logo.style.tsx
  front/src/pages/New/components/Logo/Logo.tsx
  front/src/pages/Ref/Ref.style.tsx
  front/src/pages/Ref/Ref.tsx
  front/src/pages/SignUp/SignUp.tsx
Labels: enhancement

#8 Fix : OW-21 App.tsx 빌드 에러 해결
  front/src/pages/CreateContainer/CreateContainer.tsx
  front/src/pages/EditContainer/EditContainer.tsx
  front/src/pages/FindPassword/FindPassword.tsx
  front/src/pages/Login/Login.tsx
  front/src/pages/Main/Main.tsx
  front/src/pages/MyPage/MyPage.tsx
  front/src/pages/New/components/Logo/Logo.tsx
  front/src/pages/SignUp/SignUp.tsx
Labels: bug

#10 Feat : OW-13 폰트 칼라 아이콘 보일러 플레이트
  front/src/components/Icon.tsx
  front/src/constants/color.ts
  front/src/constants/font.ts
Labels: enhancement

#15 Feat : OW-25 responsive(반응형) 컴포넌트
  front/src/components/Responsive.tsx
Labels: enhancement

#16 Feat : OW-26 FE 컨테이너 생성 페이지 UI 완료
  front/public/images/languages/c++.png
  front/public/images/languages/java.png
  front/public/images/languages/js.png
  front/public/images/languages/python.png
  front/src/pages/CreateContainer/CreateContainer.style.tsx
  front/src/pages/CreateContainer/CreateContainer.tsx
  front/src/pages/CreateContainer/components/ContainerContent/ContainerContent.style.tsx
  front/src/pages/CreateContainer/components/ContainerContent/ContainerContent.tsx
  front/src/pages/CreateContainer/components/Description/Description.style.tsx
  front/src/pages/CreateContainer/components/Description/Description.tsx
  front/src/pages/CreateContainer/components/LanguageStacks/LanguageStacks.style.tsx
  front/src/pages/CreateContainer/components/LanguageStacks/LanguageStacks.tsx
  front/src/pages/CreateContainer/components/NameInput.tsx/NameInput.style.tsx
  front/src/pages/CreateContainer/components/NameInput.tsx/NameInput.tsx
  front/src/pages/CreateContainer/components/Share/Share.style.tsx
  front/src/pages/CreateContainer/components/Share/Share.tsx
Labels: enhancement

#19 Feat : OW-33 메인 페이지 헤더 UI 작업
  front/src/components/Header/Header.style.tsx
  front/src/components/Header/Header.tsx
Labels: enhancement

#24 Feat: OW-41 컨테이너 관련 엔티티 구현
  back/src/main/java/com/ogjg/back/container/domain/Container.java
  back/src/main/java/com/ogjg/back/container/domain/UserContainerAccess.java
Labels: enhancement

#27 Feat : OW-39 회원 관리 API 및 테스트 추가
  back/src/main/java/com/ogjg/back/user/controller/UserController.java
  back/src/main/java/com/ogjg/back/user/domain/User.java
  back/src/main/java/com/ogjg/back/user/domain/UserStatus.java
  back/src/main/java/com/ogjg/back/user/dto/request/ImgUpdateRequest.java
  back/src/main/java/com/ogjg/back/user/dto/request/InfoUpdateRequest.java
  back/src/main/java/com/ogjg/back/user/dto/request/PasswordUpdateRequest.java
  back/src/main/java/com/ogjg/back/user/dto/response/ImgUpdateResponse.java
  back/src/main/java/com/ogjg/back/user/exception/NotFoundUser.java
  back/src/main/java/com/ogjg/back/user/repository/UserRepository.java
  back/src/main/java/com/ogjg/back/user/service/UserService.java
  back/src/test/java/com/ogjg/back/user/domain/UserTest.java
  back/src/test/java/com/ogjg/back/user/service/UserServiceTest.java
Labels: enhancement

#31 Feat : OW-51 rest-docs 의존성 및 html 복사 task 추가
  back/build.gradle
  back/src/docs/asciidoc/index.adoc
Labels: enhancement

#33 Feat : OW-52 회원 API mock 테스트 및 문서화 코드 작성
  back/src/docs/asciidoc/index.adoc
  back/src/main/java/com/ogjg/back/user/dto/request/InfoUpdateRequest.java
  back/src/main/java/com/ogjg/back/user/dto/request/PasswordUpdateRequest.java
  back/src/test/java/com/ogjg/back/BackApplicationTests.java
  back/src/test/java/com/ogjg/back/user/common/ControllerTest.java
  back/src/test/java/com/ogjg/back/user/controller/UserControllerTest.java
Labels: documentation, enhancement

#34 Docs : OW-55 커스텀 스니펫 추가 및 index.adoc 정리
  back/src/docs/asciidoc/index.adoc
  back/src/test/resources/org/springframework/restdocs/templates/asciidoctor/http-request.snippet
  back/src/test/resources/org/springframework/restdocs/templates/asciidoctor/http-response.snippet
  back/src/test/resources/org/springframework/restdocs/templates/asciidoctor/path-parameters.snippet
  back/src/test/resources/org/springframework/restdocs/templates/asciidoctor/query-parameters.snippet
  back/src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
  back/src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-parts.snippet
  back/src/test/resources/org/springframework/restdocs/templates/asciidoctor/response-fields.snippet
Labels: documentation

#37 Feat : OW-23 설정 파일 분리
  .gitignore
  back/src/main/resources/application.yml
Labels: duplicate

#42 Feat: OW-59 FE 비밀번호 찾기 페이지 UI
  front/src/pages/FindPassword/FindPassword.styled.tsx
  front/src/pages/FindPassword/FindPassword.tsx
Labels: enhancement

#44 Design : OW-63 메인 사이드바 UI 수정 작업
  front/package-lock.json
  front/src/components/Header/Header.tsx
  front/src/components/Icon.tsx
  front/src/components/Sidebar/Sidebar.style.tsx
  front/src/components/Sidebar/components/UserModal.style.tsx
  front/src/components/Sidebar/components/UserModal.tsx
Labels: bug

#48 Feat : OW-62 컨테이너 생성 시 디렉토리를 S3에 업로드하는 로직 추가
  back/src/main/java/com/ogjg/back/common/exception/ErrorCode.java
  back/src/main/java/com/ogjg/back/container/domain/Container.java
  back/src/main/java/com/ogjg/back/container/dto/request/ContainerCreateRequest.java
  back/src/main/java/com/ogjg/back/container/service/ContainerService.java
  back/src/main/java/com/ogjg/back/s3/exception/S3ContainerUploadException.java
  back/src/main/java/com/ogjg/back/s3/repository/S3ContainerRepository.java
  back/src/main/java/com/ogjg/back/s3/repository/S3ImageUploadRepository.java
  back/src/main/java/com/ogjg/back/s3/service/S3ContainerService.java
  back/src/main/java/com/ogjg/back/s3/service/S3ProfileImageService.java
Labels: enhancement

#50 Feat : OW-68 FE Axios 인스턴스 작업
  front/src/api/useAxios.ts
Labels: enhancement

#51 fix : deploy 중단 에러 수정
  .github/workflows/backend_cicd.yml
Labels: bug

#46 Chore : test 패키지 application.yml 추가
  back/src/test/resources/application.yml
Labels: enhancement

#56 Feat : OW - 64 컨테이너 모든 구조 가져오기 기능 구현
  back/src/main/java/com/ogjg/back/common/exception/ErrorCode.java
  back/src/main/java/com/ogjg/back/common/util/S3PathUtil.java
  back/src/main/java/com/ogjg/back/container/controller/ContainerController.java
  back/src/main/java/com/ogjg/back/container/dto/response/ContainerCheckNameResponse.java
  back/src/main/java/com/ogjg/back/container/dto/response/ContainerGetFileResponse.java
  back/src/main/java/com/ogjg/back/container/dto/response/ContainerGetNodeResponse.java
  back/src/main/java/com/ogjg/back/container/dto/response/ContainerGetResponse.java
  back/src/main/java/com/ogjg/back/container/dto/response/ContainerNodeResponse.java
  back/src/main/java/com/ogjg/back/container/dto/response/ContainerNodeResponseSerializer.java
  back/src/main/java/com/ogjg/back/container/exception/NotFoundContainer.java
  back/src/main/java/com/ogjg/back/container/service/ContainerService.java
  back/src/main/java/com/ogjg/back/s3/repository/S3ContainerRepository.java
  back/src/main/java/com/ogjg/back/s3/repository/S3ImageUploadRepository.java
  back/src/main/java/com/ogjg/back/s3/service/S3ContainerService.java
Labels: enhancement

#54 fix : 배포 관련 환경변수 설정
  .github/workflows/backend_cicd.yml
Labels: bug
