Repository Goorm-OGJG/Web-IDE, pull requests merged in 2023-10, with the labels that each got.

#61 Feat : Feat : OW - 64 컨테이너 모든 구조 가져오기 기능 수정, Controller테스트 및 문서화 작성
  back/src/docs/asciidoc/index.adoc
  back/src/main/java/com/ogjg/back/common/util/S3PathUtil.java
  back/src/main/java/com/ogjg/back/container/dto/response/ContainerGetNodeResponse.java
  back/src/main/java/com/ogjg/back/container/dto/response/ContainerNodeResponseSerializer.java
  back/src/main/java/com/ogjg/back/container/service/ContainerService.java
  back/src/main/java/com/ogjg/back/s3/service/S3ContainerService.java
  back/src/test/java/com/ogjg/back/container/controller/ContainerControllerTest.java
  back/src/test/java/com/ogjg/back/container/service/ContainerServiceTest.java
Labels: bug, enhancement

#65 Fix : 백엔드 배포 오류 수정
  .github/workflows/backend_cicd.yml
Labels: bug

#67 Feat : Cors 설정 추가
  back/src/main/java/com/ogjg/back/config/security/config/SecurityConfig.java
Labels: enhancement

#70 Feature/apiproduce
  front/package-lock.json
  front/package.json
  front/src/api/useUserAPI.ts
  front/src/pages/FindPassword/FindPassword.tsx
  front/src/pages/Login/components/LoginForm/LoginForm.style.tsx
  front/src/pages/Login/components/LoginForm/LoginForm.tsx
  front/src/pages/SignUp/SignUp.tsx
  front/src/pages/SignUp/Signup.style.tsx
  front/src/pages/SignUp/components/Password/Password.style.tsx
  front/src/pages/SignUp/components/Password/Password.tsx
  front/src/pages/SignUp/components/PasswordInput/PasswordInput.style.tsx
  front/src/pages/SignUp/components/PasswordInput/PasswordInput.tsx
  front/src/types/userAPIType.ts
Labels: enhancement

#59 Feat : OW-73 FE 컨테이너 생성 페이지 API
  front/src/api/useCreateContainerAPI.ts
  front/src/hooks/useDebounce.tsx
  front/src/pages/CreateContainer/CreateContainer.style.tsx
  front/src/pages/CreateContainer/CreateContainer.tsx
  front/src/pages/CreateContainer/components/ContainerContent/ContainerContent.style.tsx
  front/src/pages/CreateContainer/components/ContainerContent/ContainerContent.tsx
  front/src/pages/CreateContainer/components/Description/Description.tsx
  front/src/pages/CreateContainer/components/LanguageStacks/LanguageStacks.tsx
  front/src/pages/CreateContainer/components/NameInput.tsx/NameInput.style.tsx
  front/src/pages/CreateContainer/components/NameInput.tsx/NameInput.tsx
  front/src/pages/CreateContainer/components/Share/Share.tsx
Labels: enhancement

#71 Feat : OW-89 FE UUID 버그 수정
  front/package-lock.json
  front/src/pages/SignUp/SignUp.tsx
Labels: bug

#69 Refactor : 이메일 인증 주소 변경, 예외 추가
  back/src/main/java/com/ogjg/back/user/service/EmailAuthService.java
Labels: enhancement

#68 Fix : Container 엔티티 정규식 위치 수정
  back/src/main/java/com/ogjg/back/container/domain/Container.java
Labels: bug

#73 Fix : Filter 예외 오류 개선
  back/src/main/java/com/ogjg/back/config/security/emailauth/EmailAuthenticationFilter.java
  back/src/main/java/com/ogjg/back/config/security/jwt/accesstoken/AccessAuthenticationFilter.java
  back/src/main/java/com/ogjg/back/config/security/jwt/refreshtoken/RefreshTokenAuthenticationFilter.java
Labels: bug

#74 Test : OW-85 BE 비밀번호 변경 테스트에 인코딩 추가
  back/src/main/java/com/ogjg/back/user/service/UserService.java
  back/src/test/java/com/ogjg/back/user/domain/UserTest.java
  back/src/test/java/com/ogjg/back/user/service/UserServiceIntegrationTest.java
  back/src/test/java/com/ogjg/back/user/service/UserServiceTest.java
Labels: enhancement

#75 Fix : 배포서버에서 이메일 인증 템플릿 경로를 찾지 못하는 버그 수정
  back/src/main/java/com/ogjg/back/user/service/EmailAuthService.java
  back/src/main/java/com/ogjg/back/user/service/UserService.java
Labels: bug

#78 Feat : OW-82 파일/디렉토리 삭제 API 경로 전달 쿼리 파라미터를 사용하도록 수정
  back/src/docs/asciidoc/index.adoc
  back/src/main/java/com/ogjg/back/directory/controller/DirectoryController.java
  back/src/main/java/com/ogjg/back/directory/dto/request/CreateDirectoryRequest.java
  back/src/main/java/com/ogjg/back/directory/dto/request/DeleteDirectoryRequest.java
  back/src/main/java/com/ogjg/back/directory/dto/request/UpdateDirectoryNameRequest.java
  back/src/main/java/com/ogjg/back/directory/service/DirectoryService.java
  back/src/main/java/com/ogjg/back/file/controller/FileController.java
  back/src/main/java/com/ogjg/back/file/dto/request/CreateFileRequest.java
  back/src/main/java/com/ogjg/back/file/dto/request/DeleteFileRequest.java
  back/src/main/java/com/ogjg/back/file/dto/request/UpdateFileRequest.java
  back/src/main/java/com/ogjg/back/file/dto/request/UpdateFilenameRequest.java
  back/src/main/java/com/ogjg/back/file/service/FileService.java
  back/src/test/java/com/ogjg/back/container/controller/ContainerControllerTest.java
  back/src/test/java/com/ogjg/back/directory/controller/DirectoryControllerTest.java
  back/src/test/java/com/ogjg/back/file/controller/FileControllerTest.java
  back/src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-body.snippet
Labels: documentation, enhancement

#81 Feature/loginaccess token
  front/src/api/useUserAPI.ts
  front/src/pages/SignUp/SignUp.tsx
  front/src/pages/SignUp/Signup.style.tsx
  front/src/types/userAPIType.ts
Labels: enhancement

#80 Feat : OW-81 컨테이너 삭제 API 구현
  back/src/docs/asciidoc/index.adoc
  back/src/main/java/com/ogjg/back/common/util/S3PathUtil.java
  back/src/main/java/com/ogjg/back/container/controller/ContainerController.java
  back/src/main/java/com/ogjg/back/container/service/ContainerService.java
  back/src/main/java/com/ogjg/back/file/service/FileService.java
  back/src/main/java/com/ogjg/back/s3/repository/S3ContainerRepository.java
  back/src/main/java/com/ogjg/back/s3/service/S3ContainerService.java
  back/src/test/java/com/ogjg/back/container/controller/ContainerControllerTest.java
Labels: documentation, enhancement

#82 Fix : .env 환경 변수 추가
  .github/workflows/front_cicd.yaml
Labels: bug

#84 Fix : AccessToken을 검증한 후 요청 종료되는 버그 수정
  back/src/main/java/com/ogjg/back/config/security/jwt/accesstoken/AccessAuthenticationFilter.java
Labels: bug, enhancement

#87 Fix : OW-95 메인 페이지 컨테이너 조회 오류 수정
  back/src/main/java/com/ogjg/back/container/repository/ContainerRepository.java
  back/src/main/java/com/ogjg/back/container/service/ContainerService.java
Labels: bug

#89 Feat : 컨테이너 삭제 API url 수정
  back/src/main/java/com/ogjg/back/container/controller/ContainerController.java
  back/src/main/java/com/ogjg/back/container/controller/MainController.java
Labels: enhancement

#90 Feat : OW-96 FE 로그인 / 비로그인 리다이렉트 추가
  front/src/App.tsx
  front/src/components/PrivateRoute.tsx
  front/src/components/PublicRoute.tsx
  front/src/components/VoiceChat/VoiceChat.style.tsx
  front/src/components/VoiceChat/VoiceChat.tsx
  front/src/pages/EditContainer/components/Sidebar/MSidebar.tsx
  front/src/pages/MyPage/components/DeleteAccount/DeleteAccount.tsx
Labels: enhancement

#86 Fix : OW-93 회원 이미지 업로드 API 이미지 저장 경로 수정
  back/src/main/java/com/ogjg/back/common/util/S3PathUtil.java
  back/src/main/java/com/ogjg/back/s3/service/S3ProfileImageService.java
Labels: bug

#57 Feat : OW-70 코드 편집 페이지 Axios API 커스텀 훅 구현
  front/src/App.tsx
  front/src/api/useFilesAPI.ts
  front/src/hooks/CodeEditor/useFileManage.tsx
  front/src/pages/EditContainer/components/CodeEditor/CodeMirror.tsx
  front/src/pages/EditContainer/components/CodeEditor/Tab.style.tsx
  front/src/pages/EditContainer/components/CodeEditor/Tab.tsx
  front/src/pages/EditContainer/components/FsControlModals/CreateDirectoryModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/CreateFileModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/RenameDirectoryModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/RenameFileModal.tsx
  front/src/pages/EditContainer/components/Sidebar/ContextMenu.tsx
  front/src/pages/EditContainer/components/Sidebar/SidebarFileTree.tsx
  front/src/pages/EditContainer/components/Sidebar/SidebarHeader.tsx
  front/src/recoil/CodeEditorState.ts
  front/src/types/FileTree.ts
  front/src/types/filesAPIType.ts
Labels: enhancement

#94 Fix : Emitter Message가 전송되지 않는 오류 해결
  back/src/main/java/com/ogjg/back/user/controller/UserController.java
  back/src/main/java/com/ogjg/back/user/service/EmailAuthService.java
Labels: bug

#95 Feat : OW-101 이메일 인증 기능 구현
  front/src/App.tsx
  front/src/api/useUserAPI.ts
  front/src/pages/SignUp/SignUp.tsx
Labels: enhancement

#96 Feat : OW-103 FE 회원가입 인증 버튼 비활성화 및 알럿 메시지 추가
  front/src/pages/SignUp/SignUp.tsx
Labels: enhancement

#97 Fix : Filter에서 발생하는 에러가 전송되지 않는 버그
  back/src/main/java/com/ogjg/back/config/security/config/SecurityConfig.java
  back/src/main/java/com/ogjg/back/config/security/emailauth/EmailAuthenticationFilter.java
  back/src/main/java/com/ogjg/back/config/security/emailauth/EmailAuthenticationProvider.java
  back/src/main/java/com/ogjg/back/config/security/exception/AccessTokenException.java
  back/src/main/java/com/ogjg/back/config/security/exception/CustomTokenException.java
  back/src/main/java/com/ogjg/back/config/security/exception/EmailAuthTokenException.java
  back/src/main/java/com/ogjg/back/config/security/exception/RefreshTokenException.java
  back/src/main/java/com/ogjg/back/config/security/exception/handler/CustomAuthenticationEntryPoint.java
  back/src/main/java/com/ogjg/back/config/security/jwt/accesstoken/AccessAuthenticationFilter.java
  back/src/main/java/com/ogjg/back/config/security/jwt/accesstoken/AccessAuthenticationProvider.java
  back/src/main/java/com/ogjg/back/config/security/jwt/refreshtoken/RefreshAuthenticationProvider.java
  back/src/main/java/com/ogjg/back/config/security/jwt/refreshtoken/RefreshTokenAuthenticationFilter.java
  back/src/main/java/com/ogjg/back/user/exception/EmailAuthFailure.java
  back/src/main/java/com/ogjg/back/user/service/EmailAuthService.java
Labels: bug, enhancement

#98 Fix : 에러메시지의 한글깨짐 현상 해결
  back/src/main/java/com/ogjg/back/config/security/exception/handler/CustomAuthenticationEntryPoint.java
Labels: bug

#100 Fix : OW-104 폴더 삭제 시 폴더 내부에 있는 파일 탭 안닫히는 버그
  front/src/api/useFilesAPI.ts
  front/src/hooks/CodeEditor/useFileManage.tsx
Labels: bug, enhancement

#102 Fix : refreshToken 재발급 오류 현상 해결
  back/src/main/java/com/ogjg/back/config/security/jwt/refreshtoken/RefreshAuthenticationProvider.java
Labels: bug, enhancement

#103 Feat : OW-106 FE 로그아웃 기능 추가 axios 토큰 로직 추가
  front/src/api/useAxios.ts
  front/src/api/useMyAPI.ts
  front/src/components/Sidebar/components/UserModal.tsx
Labels: bug, enhancement

#101 Fix : OW-105 FE 메인 페이지 사이드바 컨테이너 스페이스 개수 검색 관련 에러 해결
  front/src/components/Sidebar/components/Space.tsx
  front/src/pages/Main/Body/components/BodyHeader.tsx
  front/src/recoil/homeState.ts
Labels: bug

#104 Fix : OW-107 FE 코드 편집 페이지 api 문서 수정에 따른 엔드포인트 변경
  front/src/api/useFilesAPI.ts
Labels: bug

#106 Fix : OW-110 컨테이너 삭제 API가 FK 제약조건에 때문에 동작하지 않는 버그 수정
  back/src/main/java/com/ogjg/back/container/domain/Container.java
  back/src/main/java/com/ogjg/back/container/service/ContainerService.java
Labels: bug

#105 Fix : OW-109 이미지 url 버그 수정
  back/src/main/java/com/ogjg/back/common/util/S3PathUtil.java
  back/src/main/java/com/ogjg/back/s3/repository/S3ImageUploadRepository.java
  back/src/main/java/com/ogjg/back/s3/service/S3ProfileImageService.java
Labels: bug

#108 Refactor : OW-111 FE UI/UX 개선
  front/src/api/useMyAPI.ts
  front/src/api/useUserAPI.ts
  front/src/components/Sidebar/Sidebar.style.tsx
  front/src/components/Sidebar/Sidebar.tsx
  front/src/components/Spinner/Spinner.style.tsx
  front/src/components/Spinner/Spinner.tsx
  front/src/components/VoiceChat/VoiceChat.style.tsx
  front/src/components/VoiceChat/VoiceChat.tsx
  front/src/pages/CreateContainer/CreateContainer.tsx
  front/src/pages/FindPassword/FindPassword.styled.tsx
  front/src/pages/FindPassword/FindPassword.tsx
  front/src/pages/SignUp/SignUp.tsx
  front/src/pages/SignUp/Signup.style.tsx
Labels: refactoring

#109 Fix : OW-116 FE token 에러
  front/src/App.tsx
  front/src/api/useAxios.ts
  front/src/components/PrivateRoute.tsx
Labels: bug

#111 Fix : OW-118 FE 빌드 에러
  front/src/components/VoiceChat/VoiceChat.tsx
Labels: bug

#112 Fix : OW-115 파일 이름 및 폴더 이름 정규식 재정의
  front/src/constants/regExp.ts
  front/src/pages/EditContainer/components/FsControlModals/CreateDirectoryModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/CreateFileModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/RenameDirectoryModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/RenameFileModal.tsx
Labels: bug, enhancement

#113 Fix : OW-119 FE 이메일 인증 UI 오류
  front/src/api/useUserAPI.ts
  front/src/pages/Login/components/LoginForm/LoginForm.tsx
  front/src/pages/MyPage/components/DeleteAccount/DeleteAccount.tsx
  front/src/pages/MyPage/components/PasswordChange/PasswordChange.tsx
  front/src/pages/MyPage/components/PasswordInput/PasswordInput.tsx
  front/src/pages/SignUp/SignUp.tsx
  front/src/pages/SignUp/Signup.style.tsx
Labels: bug

#117 Fix : OW-123 채팅 클라이언트 연결 오류 수정
  back/src/main/java/com/ogjg/back/chat/controller/MessageController.java
  back/src/main/java/com/ogjg/back/chat/repository/RoomRepository.java
  back/src/main/java/com/ogjg/back/chat/service/MessageService.java
Labels: bug, enhancement

#118 Fix : Origin을 환경변수로 적용
  back/src/main/java/com/ogjg/back/config/WebsocketConfig.java
Labels: enhancement, refactoring

#115 Refactor : OW-83 BE 파일/디렉토리 API 리팩터링
  back/src/main/java/com/ogjg/back/common/util/PathUtil.java
  back/src/main/java/com/ogjg/back/container/domain/Container.java
  back/src/main/java/com/ogjg/back/container/dto/response/ContainerGetNodeResponse.java
  back/src/main/java/com/ogjg/back/container/dto/response/ContainerNodeResponseSerializer.java
  back/src/main/java/com/ogjg/back/container/service/ContainerService.java
  back/src/main/java/com/ogjg/back/directory/service/DirectoryService.java
  back/src/main/java/com/ogjg/back/file/domain/Path.java
  back/src/main/java/com/ogjg/back/file/service/FileService.java
  back/src/main/java/com/ogjg/back/path/repository/PathRepository.java
  back/src/main/java/com/ogjg/back/path/service/PathService.java
  back/src/main/java/com/ogjg/back/s3/repository/S3ContainerRepository.java
  back/src/main/java/com/ogjg/back/s3/repository/S3DirectoryRepository.java
  back/src/main/java/com/ogjg/back/s3/repository/S3FileRepository.java
  back/src/main/java/com/ogjg/back/s3/repository/S3ImageUploadRepository.java
  back/src/main/java/com/ogjg/back/s3/service/S3ContainerService.java
  back/src/main/java/com/ogjg/back/s3/service/S3DirectoryService.java
  back/src/main/java/com/ogjg/back/s3/service/S3FileService.java
  back/src/main/java/com/ogjg/back/s3/service/S3ProfileImageService.java
Labels: refactoring

#114 Fix : OW-120 FE 컨테이너 생성 시 한글 거르지 못하는 문제
  front/src/api/useCreateContainerAPI.ts
  front/src/pages/CreateContainer/CreateContainer.tsx
Labels: bug

#119 Fix : OW-124 FE useFileMange recoil 데이터 조작 버그 해결
  front/src/api/useFilesAPI.ts
  front/src/hooks/CodeEditor/useFileManage.tsx
  front/src/pages/EditContainer/components/CodeEditor/CodeMirror.tsx
  front/src/pages/EditContainer/components/FsControlModals/CreateDirectoryModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/CreateFileModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/RenameDirectoryModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/RenameFileModal.tsx
  front/src/types/filesAPIType.ts
Labels: bug

#121 fix : OW-125 FE 폴더명에 . 사용 허용 버그 해결
  front/src/constants/regExp.ts
  front/src/pages/EditContainer/components/FsControlModals/CreateDirectoryModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/RenameDirectoryModal.tsx
Labels: bug, enhancement

#120 Fix : OW-122 컨테이너에 공개여부가 설정되지 않는 버그 수정
  back/src/main/java/com/ogjg/back/container/controller/ContainerController.java
  back/src/main/java/com/ogjg/back/container/dto/request/ContainerCreateRequest.java
  back/src/main/java/com/ogjg/back/container/dto/response/ContainerResponse.java
  back/src/main/java/com/ogjg/back/container/service/ContainerService.java
  back/src/main/java/com/ogjg/back/directory/repository/DirectoryRepository.java
  back/src/main/java/com/ogjg/back/path/service/PathService.java
  back/src/test/java/com/ogjg/back/container/controller/ContainerControllerTest.java
  back/src/test/java/com/ogjg/back/container/service/ContainerServiceTest.java
Labels: bug

#123 Feat : OW-127 파일 아이콘 색깔 변경
  front/src/components/FileIcon.tsx
Labels: bug, enhancement

#124 Fix : OW-128 파일 추가 모달, 폴더 추가 모달 오타 수정
  front/src/pages/EditContainer/components/FsControlModals/CreateDirectoryModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/CreateFileModal.tsx
Labels: bug

#125 Fix : OW-129 코드 에디터 자동완성 단축키 키맵 변경
  front/src/pages/EditContainer/components/CodeEditor/CodeMirror.tsx
Labels: bug, enhancement

#126 Fix : OW-130 에디터 뒤로가기 후 새 컨테이너 접속시 탭 상태 남아있는 버그 해결
  front/src/pages/EditContainer/components/CodeEditor/CodeEditor.tsx
Labels: bug, enhancement

#127 Fix : OW-131 코드 에디터 소개 컴포넌트 키맵 텍스트 변경
  front/src/pages/EditContainer/components/CodeEditor/EmptyActiveTap.style.tsx
  front/src/pages/EditContainer/components/CodeEditor/EmptyActiveTap.tsx
Labels: bug, enhancement

#129 Feat : OW-133 코드 편집 페이지 모달 확인, 취소 버튼 스타일 변경
  front/src/constants/color.ts
  front/src/pages/EditContainer/components/FsControlModals/CreateDirectoryModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/CreateFileModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/Modal.style.tsx
  front/src/pages/EditContainer/components/FsControlModals/RenameDirectoryModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/RenameFileModal.tsx
Labels: enhancement

#132 Fix : OW-136 없는 컨테이너 아이디로 접속 시 코드 편집 페이지 사용가능한 버그
  front/src/api/useFilesAPI.ts
Labels: bug, enhancement

#128 Feat : OW-132 EmailHistory 엔티티 추가 이메일에 발송에 대한 내역 저장, 회원 탈퇴여부 검증로직 추가
  back/src/main/java/com/ogjg/back/common/exception/ErrorResult.java
  back/src/main/java/com/ogjg/back/config/security/config/JwtTokenConfig.java
  back/src/main/java/com/ogjg/back/config/security/config/SecurityConfig.java
  back/src/main/java/com/ogjg/back/config/security/emailauth/EmailAuthenticationFilter.java
  back/src/main/java/com/ogjg/back/config/security/emailauth/EmailAuthenticationProvider.java
  back/src/main/java/com/ogjg/back/config/security/exception/AccessTokenException.java
  back/src/main/java/com/ogjg/back/config/security/exception/CustomTokenException.java
  back/src/main/java/com/ogjg/back/config/security/exception/EmailAuthTokenException.java
  back/src/main/java/com/ogjg/back/config/security/exception/RefreshTokenException.java
  back/src/main/java/com/ogjg/back/config/security/jwt/JwtUtils.java
  back/src/main/java/com/ogjg/back/config/security/jwt/accesstoken/AccessAuthenticationFilter.java
  back/src/main/java/com/ogjg/back/config/security/jwt/refreshtoken/RefreshAuthenticationProvider.java
  back/src/main/java/com/ogjg/back/config/security/jwt/refreshtoken/RefreshTokenAuthenticationFilter.java
  back/src/main/java/com/ogjg/back/user/controller/UserController.java
  back/src/main/java/com/ogjg/back/user/domain/EmailHistory.java
  back/src/main/java/com/ogjg/back/user/domain/EmailMessage.java
  back/src/main/java/com/ogjg/back/user/domain/EmailStatus.java
  back/src/main/java/com/ogjg/back/user/repository/EmailHistoryRepository.java
  back/src/main/java/com/ogjg/back/user/service/EmailAuthService.java
  back/src/main/java/com/ogjg/back/user/service/UserService.java
Labels: bug, enhancement

#134 Fix : 코드 에디터 소개 컴포넌트 키맵 변경 - 모바일
  front/src/pages/EditContainer/components/CodeEditor/EmptyActiveTap.tsx
Labels: bug, enhancement

#137 Fix : OW-137 프로필 이미지 에러 수정
  front/src/pages/MyPage/components/ProfileImg/ProfileImg.tsx
Labels: bug

#139 Fix : OW-141 FE 메인 페이지 QA-2 버그 수정
  front/src/components/Sidebar/components/UserModal.tsx
  front/src/pages/Main/Body/Body.style.tsx
  front/src/pages/Main/Body/components/Container.tsx
  front/src/pages/Main/Body/components/ContainerSettingModal.tsx
Labels: bug

#136 Fix : OW-140 회원 비밀번호 요청 값 정규표현식 수정
  back/src/main/java/com/ogjg/back/user/dto/request/LoginRequest.java
  back/src/main/java/com/ogjg/back/user/dto/request/PasswordUpdateRequest.java
  back/src/main/java/com/ogjg/back/user/dto/request/SignUpRequest.java
Labels: bug

#140 Fix : 회원 탈퇴시 재가입이 안되던 버그 수정, RefreshTokenCookie 수정
  back/src/main/java/com/ogjg/back/user/controller/UserController.java
  back/src/main/java/com/ogjg/back/user/domain/EmailAuth.java
  back/src/main/java/com/ogjg/back/user/domain/User.java
  back/src/main/java/com/ogjg/back/user/service/EmailAuthService.java
  back/src/main/java/com/ogjg/back/user/service/UserService.java
Labels: bug, enhancement

#141 Fix : OW-143 채팅목록 가져오기 에러 수정
  back/src/main/java/com/ogjg/back/chat/repository/MessageRepository.java
  back/src/main/java/com/ogjg/back/chat/repository/RoomRepository.java
  back/src/main/java/com/ogjg/back/chat/service/MessageService.java
Labels: bug, enhancement

#143 Fix : 채팅 목록 조회 시 발생 에러 수정
  back/src/main/java/com/ogjg/back/chat/service/MessageService.java
Labels: bug

#142 Chore : Accesstoken 시간 임시변경
  back/src/main/java/com/ogjg/back/config/security/jwt/JwtUtils.java
Labels: enhancement

#146 Fix : OW-146 FE Build 에러 발생
  front/src/pages/CreateContainer/components/Share/Share.style.tsx
  front/src/pages/EditContainer/components/FsControlModals/CreateDirectoryModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/CreateFileModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/RenameDirectoryModal.tsx
  front/src/pages/EditContainer/components/FsControlModals/RenameFileModal.tsx
Labels: bug

#148 Feat : OW-144 채팅 기능 구현
  front/src/pages/EditContainer/components/Sidebar/MSidebar.1.tsx
Labels: enhancement

#145 Refactor : OW-145 Path 엔티티 S3Entry로 이름 변경
  back/src/main/java/com/ogjg/back/container/domain/Container.java
  back/src/main/java/com/ogjg/back/container/service/ContainerService.java
  back/src/main/java/com/ogjg/back/directory/service/DirectoryService.java
  back/src/main/java/com/ogjg/back/file/service/FileService.java
  back/src/main/java/com/ogjg/back/s3entry/domain/S3Entry.java
  back/src/main/java/com/ogjg/back/s3entry/repository/S3EntryRepository.java
  back/src/main/java/com/ogjg/back/s3entry/service/S3EntryService.java
  back/src/test/java/com/ogjg/back/container/service/ContainerServiceTest.java
Labels: refactoring

#147 Fix : OW-147 FE token 에러
  front/src/api/useUserAPI.ts
Labels: bug

#150 Fix : 도메인 주소 변경으로 인한 CORS 설정 변경
  back/src/main/java/com/ogjg/back/config/security/config/SecurityConfig.java
  back/src/main/java/com/ogjg/back/user/service/UserService.java
Labels: bug, enhancement

#152 Fix : OW-148 FE link 경로 및 중복 요청 수정
  front/src/api/useCreateContainerAPI.ts
  front/src/api/useMyAPI.ts
  front/src/api/useUserAPI.ts
  front/src/pages/CreateContainer/CreateContainer.tsx
  front/src/pages/FindPassword/FindPassword.tsx
  front/src/pages/Login/components/LoginForm/LoginForm.tsx
  front/src/pages/MyPage/components/DeleteAccount/DeleteAccount.tsx
  front/src/pages/MyPage/components/PasswordChange/PasswordChange.tsx
  front/src/pages/MyPage/components/ProfileImg/ProfileImg.tsx
  front/src/pages/MyPage/components/UserInfo/UserInfo.tsx
  front/src/pages/SignUp/SignUp.tsx
Labels: bug

#153 Fix : OW-149 코드 편집 페이지 저장 기능 삭제
  front/src/pages/EditContainer/components/CodeEditor/CodeEditor.tsx
  front/src/pages/EditContainer/components/Sidebar/MSidebar.tsx
Labels: bug, enhancement

#154 Feat : OW-150 FE SEO 추가
  front/index.html
  front/public/ogimage.png
  front/public/vite.svg
Labels: enhancement

#155 Fix : OW-151 채팅 메시지에 이미지 정보를 반환하도록 변경
  back/src/main/java/com/ogjg/back/chat/domain/Message.java
  back/src/main/java/com/ogjg/back/chat/dto/MessageDto.java
  back/src/main/java/com/ogjg/back/chat/service/MessageService.java
Labels: bug, enhancement

#156 Fix : OW-150 name property로 변경
  front/index.html
Labels: bug

#158 Fix : Domain 주소 삭제
  back/src/main/java/com/ogjg/back/user/service/UserService.java
Labels: enhancement

#159 Fix : OW-153 FE 채팅 및 메인페이지 QA 3차 수정
  front/src/api/useChat.ts
  front/src/api/useContainerAPI.ts
  front/src/components/Chat/Chat.tsx
  front/src/components/Chat/components/ChatBody.tsx
  front/src/components/Sidebar/components/Space.tsx
  front/src/components/Sidebar/components/UserModal.tsx
  front/src/components/VoiceChat/VoiceChat.tsx
  front/src/pages/CreateContainer/CreateContainer.tsx
  front/src/pages/Main/Body/components/BodyHeader.tsx
  front/src/pages/Main/Body/components/ContainerDeleteModal.tsx
  front/src/types/chat.ts
Labels: bug
